### ISSUE TITLE
using comments to pre-answer linting things...

### ISSUE THREAD

**Issue by gregglind** [mozilla/shield-studies-addon-utils#24]
for example:  /\* shield: telemetry something _/ or /_shield: surveyurl whatever */

**Comment by gregglind** [comment]
maybe `package.json` stuff.  

I sure wish that node could run tests on this stuff :(  

```
shield-study:
   - study:  [some/path,   some.id]
   - surveyUrls
   - name
   - duration
   - variations  ????
      blah-1:  [some/path, id]
      blah-2: [some/path, otherId]  
```

I wonder if just having a test that is:  ```  require(the/study).ourStudy.lint() ``` as a test makes sense?
